name: "Continuous Deployment"

on:
  push:
    branches: ["main"]

jobs:
  infra-and-build:
    runs-on: self-hosted
    environment: vps-production
    outputs:
      api_id: ${{ steps.get-api-id.outputs.id }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Psycopg2 Layer
        run: |
          LAYER_PATH="layers/psycopg2_layer/python/lib/python3.12/site-packages"
          mkdir -p "$LAYER_PATH"
          python3.12 -m pip install --upgrade psycopg2-binary==2.9.11 -t "$LAYER_PATH"
          find layers/psycopg2_layer -name "__pycache__" -type d -exec rm -rf {} +

      - name: Terraform Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ vars.AWS_REGION }}
          TF_VAR_aws_access_key: ${{ secrets.TF_VAR_AWS_ACCESS_KEY }}
          TF_VAR_aws_secret_key: ${{ secrets.TF_VAR_AWS_SECRET_KEY }}
          TF_VAR_aws_region: ${{ vars.TF_VAR_AWS_REGION }}
          TF_VAR_db_password: ${{ secrets.TF_VAR_DB_PASSWORD }}
          TF_VAR_db_username: ${{ vars.TF_VAR_DB_USERNAME }}
          TF_VAR_db_indentifier: ${{ vars.TF_VAR_DB_INDENTIFIER }}
          TF_VAR_db_engine: ${{ vars.TF_VAR_DB_ENGINE }}
          TF_VAR_db_engine_version: ${{ vars.TF_VAR_DB_ENGINE_VERSION }}
          TF_VAR_db_instance_class: ${{ vars.TF_VAR_DB_INSTANCE_CLASS }}
          TF_VAR_db_allocated_storage: ${{ vars.TF_VAR_DB_ALLOCATED_STORAGE }}
        run: |
          cd terraform
          tflocal init
          tflocal apply -auto-approve

      - name: Get API ID
        id: get-api-id
        run: |
          API_ID=$(awslocal apigateway get-rest-apis --query "items[?name=='telemetry-api'].id" --output text | head -n 1)

          if [ -z "$API_ID" ] || [ "$API_ID" == "None" ]; then
            echo "ERRO: API ID não encontrado no LocalStack!"
            exit 1
          fi
          echo "id=$API_ID" >> $GITHUB_OUTPUT

      - name: Generate Frontend .env
        run: |
          mkdir -p web
          echo "VITE_REST_URL=http://${{ vars.DOMAIN }}:4566/restapis/${{ steps.get-api-id.outputs.id }}/dev/_user_request_/telemetry" > web/.env
          echo "VITE_WS_URL=ws://${{ vars.DOMAIN }}:4510/dev" >> web/.env

          ls -la web/.env
          cat web/.env

      - name: Upload .env as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-env
          path: ./web/.env

  database-migrations:
    runs-on: self-hosted
    needs: infra-and-build
    environment: vps-production
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run SQL Migrations
        env:
          PGPASSWORD: ${{ secrets.DB_PASSWORD }}
        run: |
          psql -h ${{ vars.DB_HOST }} -p ${{ vars.DB_PORT }} -U ${{ vars.DB_USER }} -d ${{ vars.DB_NAME }} -f ./sql/init.sql

  docker-deploy:
    runs-on: self-hosted
    needs: infra-and-build
    environment: vps-production
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Download .env Artifact
        uses: actions/download-artifact@v4
        with:
          name: frontend-env
          path: ./web/

      - name: Verify .env location
        run: ls -la ./web/

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Frontend Image
        uses: docker/build-push-action@v5
        with:
          context: ./web
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/industrial-web:latest

      - name: Deploy Image on VPS Docker
        run: |
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/industrial-web:latest
          docker stop industrial-web || true
          docker rm industrial-web || true
          docker run -d \
            --name industrial-web \
            -p 80:80 \
            --network host \
            ${{ secrets.DOCKERHUB_USERNAME }}/industrial-web:latest
